### ISSUE TITLE
Remove Dependency on Calidog's CertStream Server

### ISSUE THREAD

**Issue by Azathothas** [Azathothas/CertStream-Domains#6]
Reasons:
- https://certstream.calidog.io/ is unrelaible, frequent 521 & disconnects 
- https://github.com/CaliDog/certstream-python/issues/60
- https://github.com/CaliDog/certstream-server/issues/110

Proposal:
- Use https://github.com/d-Rickyy-b/certstream-server-go as the server
- Use https://github.com/Azathothas/Arsenal/tree/main/certstream as the client
- Be completely self-reliant for both server & client

**Comment by Azathothas** [comment]
Works as expected : https://github.com/Azathothas/CertStream-Domains/commit/e8bc7bbebaeb51f1e2c073aacf5987a440297d13
[+] https://github.com/Azathothas/CertStream-Domains/commit/08298151a3a6dcc1664ef75d4d8e9d3e443e8711
[+] https://github.com/Azathothas/CertStream-Domains/commit/def221f610c811007916435e9d7144c952ee5d87
[+] https://github.com/Azathothas/CertStream-Domains/commit/1214561b14ba36d378cf73f0c0173f8fc4ec87e8

**Comment by r0bb3d** [comment]
Good stuff, thanks for pointing us in the right direction!
